################################################################################
#							FaustWeb LINUX script
#  The behaviour of this Makefile will only be correct if
#  only one .dsp file exists in the folder
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2unity -source "$(faustfile)"
	zip -r binary.zip FaustPlugin*

src.cpp : $(faustfile)
	faust -uim -i -a unity.cpp $(faustfile) -o src.cpp

