################################################################################
#							FaustWeb OSX script
#  The behaviour of this Makefile will only be correct if
#  only one .dsp file exists in the folder
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2unity $(faustfile) -w64 $(OPT)
	zip -r binary.zip *.unitypackage

src.cpp : $(faustfile)
	faust -i -a unity.cpp $(faustfile) -o src.cpp
