################################################################################
# 
#			FaustWeb Makefile for WebAudio+wasm applications
# 
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2webaudiowasm -worklet -poly $(faustfile)
	zip -r binary.zip $(faustfile:.dsp=.html) $(faustfile:.dsp=.wasm) $(faustfile:.dsp=-processor.js) 

src.cpp : $(faustfile)
	faust -lang wasm-e -i -a webaudio/webaudio-workletnode-poly-standalone-wrapper.js $(faustfile) -o src.wasm
