################################################################################
# 
#			FaustWeb Makefile for wasm applications
# 
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2wasm $(faustfile)
	zip -r binary.zip $(faustfile:.dsp=.js) $(faustfile:.dsp=.wasm)

src.cpp : $(faustfile)
	faust -lang wasm -i -a webaudio/webaudio-asm-standalone-wrapper.js $(faustfile) -o src.js
