################################################################################
# 
#			FaustWeb Makefile for wasm applications
# 
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2wasm -worklet $(faustfile)
	zip -r binary.zip $(faustfile:.dsp=.js) $(faustfile:.dsp=-processor.js)

src.cpp : $(faustfile)
	faust -lang wasm -i -a webaudio/webaudio-wasm-standalone-wrapper.js $(faustfile) -o src.js
