#FaustBinaryTarget: index.html
################################################################################
# 
#		FaustWeb Makefile for PWA applications using TS architecture
# 
################################################################################

faustfile ?= $(wildcard *.dsp)
out ?= '.'

index.html : $(faustfile)
	faust2wasm-ts $(faustfile) $(out) -pwa
	touch $(out)/faust-ui/Makefile
	touch $(out)/faustwasm/Makefile

binary.zip : $(faustfile)
	faust2wasm-ts $(faustfile) ./app -pwa
	touch ./app/faust-ui/Makefile
	touch ./app/faustwasm/Makefile
	zip -r binary.zip ./app


src.wasm : $(faustfile)
	faust -lang wasm -i $(faustfile) -o src.wasm
