################################################################################
# 
#			FaustWeb Makefile for asm.js applications
# 
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2asmjs $(faustfile)
	zip -r binary.zip $(faustfile:.dsp=.js) 

src.cpp : $(faustfile)
	faust -lang ajs -i -a webaudio/webaudio-asm-standalone-wrapper.js $(faustfile) -o src.js
