################################################################################
# 
#		FaustWeb Makefile for WebAudio+wasm applications using TS architecture
# 
################################################################################

faustfile ?= $(wildcard *.dsp)
out ?= $(basename $(faustfile))

binary.zip : $(faustfile)

	faust2wasm-ts $(faustfile) $(out) -standalone  
	zip -r binary.zip $(out)

src.wasm : $(faustfile)
	faust -lang wasm -i $(faustfile) -o src.wasm
