################################################################################
# 
#			FaustWeb Makefile for WAP (Web Audio Plugin)
# 
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2wam -poly $(faustfile) $(faustfile)-wam  
	zip -r binary.zip $(faustfile)-wam

src.cpp : $(faustfile)
	faust -lang wasm -i $(faustfile) -o src.js
