################################################################################
# 
#			FaustWeb Makefile for WebAudio+asm.js applications
# 
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2webaudioasm -poly $(faustfile)
	zip -r binary.zip $(faustfile:.dsp=.html) 

src.cpp : $(faustfile)
	faust -lang ajs -i -a webaudio/webaudio-asm-poly-standalone-wrapper.js $(faustfile) -o src.js
