################################################################################
# 
#			FaustWeb Makefile for WAP (Web Audio Plugin)
# 
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2wam -fft $(faustfile) $(faustfile)-wam  
	#zip -r binary.zip $(faustfile)-wam
	cd $(faustfile)-wam && zip -r binary.zip * && cp binary.zip ..

src.cpp : $(faustfile)
	faust -lang wasm -i $(faustfile) -o src.js
