#!/bin/bash

#USAGE : test <architecture>

rm -rf sandbox
rm -rf build-Makefile.*
rm -f LOG
for f in *.dsp; do
	echo "test file $f with $1 architecture"
	for m in "../makefiles/$1/Makefile".*; do
		echo -n "compile $f with $m : "
		rm -rf sandbox
		mkdir sandbox
		cp $f sandbox/
		cp $m sandbox/Makefile
		cd sandbox
		((make binary.zip  >> ../LOG 2>&1) && echo "passed" ) || echo "failed"
		cd ..
		mv sandbox build-$(basename $m)
	done
done
