################################################################################
#
#			FaustWeb Makefile for the Bela board
#
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2bela -osc -midi -nvoices 4 -effect auto $(faustfile)
	zip -r binary.zip $(faustfile:.dsp=)

src.cpp : $(faustfile)
	faust -i -a bela.cpp $(faustfile) -o src.cpp
