################################################################################
#
#			FaustWeb Makefile for JUCE
#
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2juce -midi -jsynth -nvoices 16 $(faustfile)
	zip -r binary.zip $(faustfile:.dsp=)

src.cpp : $(faustfile)
	faust -i -a juce-plugin.cpp $(faustfile) -o src.cpp
