################################################################################
#
#			FaustWeb Makefile for JUCE
#
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2juce -standalone -midi -osc $(faustfile)
	zip -r binary.zip $(faustfile:.dsp=)

src.cpp : $(faustfile)
	faust -i -a juce-standalone.cpp $(faustfile) -o src.cpp
