################################################################################
#							FaustWeb OSX script 
#  The behaviour of this Makefile will only be correct if
#  only one .dsp file exists in the folder
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	remoteOSX faust2puredata $(faustfile) $(OPT)

src.cpp : $(faustfile)
	faust -i -a puredata.cpp $(faustfile) -o src.cpp

