#!/bin/bash

#USAGE : rfaust <servurl> ==> <targets>
#USAGE : rfaust <servurl> <platform> <arch> <srcfile> ==> <binary.zip>

function targetrequest {
    curl  "$1/targets"
}

function compilation {
    curl -F"file=@\"$4\";filename=\"$4\""  "$1/compile/$2/$3/binary.zip" --output binary.zip
    unzip -o binary.zip
}


if [ "$#" == "1" ]; then
    targetrequest "$1"
elif [ "$#" == "4" ]; then
    if [ -f "$4" ]; then
	    compilation $1 $2 $3 $4
    else 
        echo "ERROR: file $4 doesn't exist"
        exit 1
    fi
else
    echo "usage : $0 <servurl> [<platform> <arch> <srcfile>]"
fi 

