#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=linux
#ARCHLIST="alsa-gtk-64bits alsa-qt-64bits csound-64bits dssi-64bits jack-console-64bits jack-gtk-64bits jack-qt-64bits ladspa-64bits lv2-64bits lv2-64bits-qt4 lv2-64bits-qt5 matlabplot-64bits plot puredata-64bits puredata-poly-64bits supercollider-64bits vst-64bits vst-64bits-qt4 vst-64bits-qt5"
ARCHLIST="alsa-gtk-64bits alsa-qt-64bits csound-64bits dssi-64bits jack-console-64bits jack-gtk-64bits jack-qt-64bits ladspa-64bits lv2-64bits lv2-64bits-qt4 lv2-64bits-qt5 matlabplot-64bits plot puredata-64bits puredata-poly-64bits supercollider-64bits vst-64bits"

echo "$PLATFORM"
for ARCH in $ARCHLIST; do
    echo
	echo "$PLATFORM/$ARCH"
	./rfaust $SERVICE $PLATFORM $ARCH kisana.dsp
done