#!/bin/bash

# Enviroment variable that can be set a default faustservice url
[ ! -z "$1" ] && SERVICE="$1" || SERVICE=${CLOUDSERVICE:="https://faustservicecloud.grame.fr"}

PLATFORM=source
ARCHLIST="api-android api-ios api-poly-android api-poly-ios cplusplus juce juce-poly smartkeyb-android smartkeyb-ios"

echo "$PLATFORM"
for ARCH in $ARCHLIST; do
    echo
	echo "$PLATFORM/$ARCH"
	./rfaust $SERVICE $PLATFORM $ARCH kisana.dsp
done