################################################################################
#							FaustWeb OSX script
#  The behaviour of this Makefile will only be correct if
#  only one .dsp file exists in the folder
################################################################################

faustfile	?= $(wildcard *.dsp)
faustcpp    ?= $(faustfile:.dsp=.cpp)
faustso     ?= $(faustfile:.dsp=.so)

binary.zip : $(faustfile)
	faust -i -a stratus.cpp -scn FaustDSP -light -nvi $(faustfile) -o $(faustcpp)
	docker run -v .:/tmp chaos-stratus-effect-build \
	c++ -fPIC -shared -O3 -mfloat-abi=hard -mfpu=neon -ftree-vectorize -ffast-math -fprefetch-loop-arrays -funroll-loops -funsafe-loop-optimizations -fno-finite-math-only \
	/tmp/$(faustcpp) -o /tmp/$(faustso)
	zip -r binary.zip $(faustfile) $(faustcpp) $(faustso)

src.cpp : $(faustfile)
	faust -i -a stratus.cpp -scn FaustDSP -light -nvi $(faustfile) -o src.cpp
