################################################################################
#							FaustWeb OSX script
#  The behaviour of this Makefile will only be correct if
#  only one .dsp file exists in the folder
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2vst $(OPT) $(faustfile)
	zip -r binary.zip $(faustfile:.dsp=.vst)

src.cpp : $(faustfile)
	faust -i -a vst2p4.cpp $(faustfile) -o src.cpp
