################################################################################
#							FaustWeb Stratus binary build script
#  The behaviour of this Makefile will only be correct if
#  only one .dsp file exists in the folder
################################################################################

faustfile	?= $(wildcard *.dsp)
faustcpp    ?= $(faustfile:.dsp=.cpp)
faustid     := $(shell sed -n 's/^\s*declare\s\s*stratusId\s\s*"\([0-9a-f]\{8\}-[0-9a-f]\{4\}-[0-9a-f]\{4\}-[0-9a-f]\{4\}-[0-9a-f]\{12\}\)";/\1/p' "$(faustfile)")
faustver    := $(shell sed -n 's/^\s*declare\s\s*version\s\s*"\([^"]*\)";/\1/p' "$(faustfile)")
faustso     ?= $(if $(faustid),$(faustid).so,$(faustfile:.dsp=.so))
fausttxt    := $(if $(faustid),$(if $(faustver),$(faustid).txt,),)
CXXFLAGS    := -fPIC -shared -O3 -mfloat-abi=hard -mfpu=neon -ftree-vectorize -ffast-math -fprefetch-loop-arrays -funroll-loops -funsafe-loop-optimizations -fno-finite-math-only

binary.zip : $(faustso) $(fausttxt)
	@zip -r binary.zip $(faustfile) $(faustcpp) $(faustso) $(fausttxt)
	@rm -rf $(faustcpp) $(faustso) $(fausttxt)

$(faustso) : $(faustcpp)
	dockerStratus c++ $(CXXFLAGS) /tmp/$(faustcpp) -o /tmp/$(faustso)

$(faustcpp) : $(faustfile)
	faust2stratus -nocppc $(faustfile) -o $(faustcpp)

$(fausttxt): 
	echo -n $(faustver) > $(fausttxt)
