################################################################################
#           FaustWeb Stratus effect installer script
#  The behaviour of this Makefile will only be correct if
#  only one .dsp file exists in the folder
################################################################################

faustfile	?= $(wildcard *.dsp)
faustarch   := $(shell faust -archdir)
effectcpp   ?= $(faustfile:.dsp=.cpp)
effectso    ?= $(faustfile:.dsp=.so)
installer   := install.sh
zipcontent  := $(faustfile) $(effectcpp) $(installer) _pedal-tools.sh README.txt

binary.zip : $(zipcontent)
	zip -r binary.zip $(zipcontent)

$(effectcpp) : src.cpp
	cp src.cpp $(effectcpp)

$(installer) : $(effectcpp)
	@echo "EFFECT_DSP=$(faustfile)" > $(installer)
	@echo "EFFECT_CPP=$(effectcpp)" >> $(installer)
	@echo "EFFECT_SO=$(effectso)" >> $(installer)
	@cat $(faustarch)/chaos-stratus/build-install-effect.sh >> $(installer)
	@chmod +x $(installer)	

_pedal-tools.sh: $(faustarch)/chaos-stratus/_pedal-tools.sh
	@cp  $(faustarch)/chaos-stratus/_pedal-tools.sh .

README.txt: $(faustarch)/chaos-stratus/README.txt
	@cp  $(faustarch)/chaos-stratus/README.txt .

src.cpp : $(faustfile)
	faust2stratus -nocppc $(faustfile) -o src.cpp
