################################################################################
#							FaustWeb LINUX script
#  The behaviour of this Makefile will only be correct if
#  only one .dsp file exists in the folder
################################################################################

faustfile	?= $(wildcard *.dsp)

binary.zip : $(faustfile)
	faust2supercollider -noprefix -sn $(OPT) $(faustfile)
	zip -r binary.zip $(faustfile:.dsp=.so) $(faustfile:.dsp=.sc)

src.cpp : $(faustfile)
	faust -i -a supercollider.cpp $(faustfile) -o src.cpp
